openapi: 3.0.0
info:
  title: Virtual Credit Rails API
  version: 1.0.0
  description: OpenAPI for Virtual Credit Rails API
  contact:
    email: virtualcredit.official@gmail.com
    name: admin
servers:
  - url: 'http://localhost:4000/api'
tags:
  - name: ReleaseNote
    description: リリースノートに関するAPI
  - name: Authentication
    description: 認証に関するAPI
components:
  securitySchemes: {}
  schemas:
    Pagination:
      title: Pagination
      x-stoplight:
        id: n2bdaewgmjspr
      type: object
      properties:
        hasNext:
          type: boolean
          x-stoplight:
            id: d3ybcecx147m8
        hasPrevious:
          type: boolean
          x-stoplight:
            id: b6aygypylv4zf
        currentPage:
          type: integer
          x-stoplight:
            id: obdz7vxhz8o52
        totalPages:
          type: integer
          x-stoplight:
            id: oftt6zy92c0w7
        totalCount:
          type: integer
          x-stoplight:
            id: bema3583qynnb
      required:
        - hasNext
        - hasPrevious
        - currentPage
        - totalPages
        - totalCount
      x-examples: {}
    ReleaseNote:
      title: ReleaseNote
      x-stoplight:
        id: oupyewy02383q
      type: object
      properties:
        id:
          type: string
        version:
          type: string
          x-stoplight:
            id: 5rr8wkdsv8cw2
        title:
          type: string
          x-stoplight:
            id: gujhci7o78ufq
        description:
          type: string
          x-stoplight:
            id: 7f0nw7jlwgb3d
        createdAt:
          type: string
          x-stoplight:
            id: rlwyvjkwdvwmu
          format: date-time
      required:
        - id
        - version
        - title
        - description
        - createdAt
      x-examples: {}
    Error:
      title: Error
      x-stoplight:
        id: yaeqhcu06c8j1
      type: object
      properties:
        message:
          type: string
          x-stoplight:
            id: y59gxc86odxqz
        resource:
          type: string
          x-stoplight:
            id: oedpyfp0krt6b
        code:
          type: integer
          x-stoplight:
            id: kh944euclth3n
        errors:
          type: array
          x-stoplight:
            id: exuao25m3o6ex
          items:
            x-stoplight:
              id: urr0xqy1j3mdi
            type: object
            properties:
              field:
                type: string
                x-stoplight:
                  id: 8yqmizf5lp9kk
              message:
                type: string
                x-stoplight:
                  id: mvq0kx7yf06h7
            required:
              - field
              - message
      required:
        - message
        - resource
        - code
        - errors
    User:
      title: User
      x-stoplight:
        id: 0z5z5va8lnrhm
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          x-stoplight:
            id: 3y2gz6l4jxs97
          nullable: true
        image:
          type: string
          x-stoplight:
            id: 7pyyfe3pdjgow
          nullable: true
        slug:
          type: string
          x-stoplight:
            id: irddytld7o36a
          nullable: true
        description:
          type: string
          x-stoplight:
            id: pd1loyvcnrxl3
          nullable: true
        published:
          type: boolean
          x-stoplight:
            id: asn2cjhnqru9m
        provider:
          type: string
          x-stoplight:
            id: wum4lff3d9y8l
          nullable: true
        uid:
          type: string
          x-stoplight:
            id: eg5u2hyw4625r
          nullable: true
        email:
          type: string
          x-stoplight:
            id: 1e5fvjbaiqwad
          nullable: true
        activated_at:
          type: string
          x-stoplight:
            id: hssj4q6nam62h
          format: date-time
          nullable: true
        created_at:
          type: string
          x-stoplight:
            id: 52qrzsizqhrjx
          format: date-time
          nullable: true
        updated_at:
          type: string
          x-stoplight:
            id: 1sti645z8bbxm
          format: date-time
          nullable: true
      required:
        - id
        - name
        - image
        - slug
        - description
        - published
        - provider
        - uid
        - email
        - activated_at
        - created_at
        - updated_at
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              value:
                message: Request failed
                resource: User
                code: 400
                errors:
                  - field: page
                    message: pageは数字で入力してください。
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              value:
                message: Validation failed
                resource: User
                code: 422
                errors:
                  - field: name
                    message: ユーザー名の入力は必須です。
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Example 1:
              value:
                message: Resource conflicted
                resource: User
                code: 409
                errors:
                  - field: email
                    message: 既にメールアドレスが使用されています。
    DeviseRegistrationSuccess:
      description: Devise Registration Success
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                x-stoplight:
                  id: 1df1f6n3nptzf
              data:
                $ref: '#/components/schemas/User'
            required:
              - status
              - data
          examples:
            Example 1:
              value:
                status: success
                data:
                  id: ba4367ee-e54c-4976-8c53-513c893fb418
                  name: null
                  image: null
                  slug: null
                  description: null
                  published: false
                  provider: email
                  uid: test@example.com
                  email: test@example.com
                  activatedAt: '2019-08-24T14:15:22Z'
                  createdAt: '2019-08-24T14:15:22Z'
                  updatedAt: '2019-08-24T14:15:22Z'
    DeviseRegistrationFailed:
      description: Devise Registration Failed
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                x-stoplight:
                  id: 0uprqalfazxjl
              data:
                $ref: '#/components/schemas/User'
              errors:
                type: object
                x-stoplight:
                  id: 5elkl44ti26zw
                properties:
                  email:
                    type: array
                    x-stoplight:
                      id: na304dvv82obv
                    items:
                      x-stoplight:
                        id: oz6ni9l2gx8ti
                      type: string
                  password:
                    type: array
                    x-stoplight:
                      id: 0875txw0e51cb
                    items:
                      x-stoplight:
                        id: xem6mb6x039na
                      type: string
                  password_confirmation:
                    type: array
                    x-stoplight:
                      id: 75c1vncad2mr4
                    items:
                      x-stoplight:
                        id: 2ef1wp12q87xp
                      type: string
                  full_messages:
                    type: array
                    x-stoplight:
                      id: 0ev6q36bx7q8e
                    items:
                      x-stoplight:
                        id: 7dyypcgn2njdf
                      type: string
          examples:
            Example 1:
              value:
                status: error
                data:
                  id: null
                  name: null
                  image: null
                  slug: null
                  description: null
                  published: false
                  provider: email
                  uid: ''
                  email: test@example.com
                  activated_at: '2019-08-24T14:15:22Z'
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
                errors:
                  email:
                    - を入力してください
                    - はすでに存在します
                  password:
                    - を入力してください
                  password_confirmation:
                    - とパスワードの入力が一致しません
                  full_messages:
                    - Eメールはすでに存在します
                    - パスワードは24文字以内で入力してください
  examples: {}
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: 取得したいページ数
paths:
  /v1/release_notes:
    get:
      summary: リリースノート一覧
      tags:
        - ReleaseNote
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    x-stoplight:
                      id: rb1sb9jr5d19w
                    items:
                      $ref: '#/components/schemas/ReleaseNote'
                  meta:
                    $ref: '#/components/schemas/Pagination'
                required:
                  - data
                  - meta
              examples:
                Example 1:
                  value:
                    data:
                      - id: dk54-1222-fnd1-dk1a
                        version: 1.0.1
                        title: New Release
                        description: 新機能がリリースされまｓｈちあ
                        createdAt: '2019-08-24T14:15:22Z'
                    meta:
                      hasNext: true
                      hasPrevious: true
                      currentPage: 1
                      totalPages: 10
                      totalCount: 100
        '400':
          $ref: '#/components/responses/BadRequest'
      operationId: get-v1-release-notes
      description: リリースノートの一覧を返す
      parameters:
        - $ref: '#/components/parameters/page'
    parameters: []
  /v1/auth:
    post:
      summary: ユーザー登録
      operationId: post-v1-auth
      responses:
        '200':
          $ref: '#/components/responses/DeviseRegistrationSuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/DeviseRegistrationFailed'
      description: 未認証状態のユーザーを登録する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  x-stoplight:
                    id: 5gnmpioukq5zs
                password:
                  type: string
                  x-stoplight:
                    id: g5yr3pzzba2at
                passwordConfirmation:
                  type: string
                  x-stoplight:
                    id: poi8c209kjif7
                confirmSuccessUrl:
                  type: string
                  x-stoplight:
                    id: l27wu2d2mfcyu
              required:
                - email
                - password
                - passwordConfirmation
                - confirmSuccessUrl
            examples:
              Example 1:
                value:
                  email: hogehoge@fuga.com
                  password: password
                  passwordConfirmation: password
                  confirmSuccessUrl: 'https://google.com'
      tags:
        - Authentication
